server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:        #http://127.0.0.1:${server.port}/eureka
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-renewal-interval-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
# 编写FastDFS属性
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址(服务器地址配置列表)
      - 192.168.56.101:22122
ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
      - image/jepg
      - image/png
      - image/bmg


